name: CensoredLib
description: A library created for use with Censored Software's Bukkit/Spigot/Minecraft related projects.
main: com.censoredsoftware.censoredlib.CensoredLibPlugin
version: ${parent.version}
softdepend: [WorldEdit, WorldGuard]
authors: [_Alex, HmmmQuestionMark]
