name: CensoredLib
description: A library created for use with Censored Software's Bukkit/Spigot/Minecraft related projects.
main: com.censoredsoftware.plugin.CensoredLibPlugin
version: ${parent.version}
softdepend: [WorldEdit, WorldGuard]
authors: [_Alex, HmmmQuestionMark]
commands:
    repo:
        usage: /repo [option] [args]
        permission: censoredlib.basic